set -g mouse on
# Status bar
set -g status-bg black
set -g status-fg white
set-option -g status-justify centre
set-option -g status-left '#[fg=cyan][#{session_name}]'
set-option -g status-right '#{prefix_highlight} | %a %Y-%m-%d %H:%M'
set-option -g status-left-length 25

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'


run '~/.tmux/plugins/tpm/tpm'

